fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
  symlinks:
    puppet_config: "#{source_dir}"
